name: github-actions
run-name: ${{ github.actor }} is pulling code!!! :)
on: [pull_request]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Super-Linter
      uses: github/super-linter@v4.9.6
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
